#ifndef ICEPALETTE_H
#define ICEPALETTE_H 1

const unsigned char IcePalette[13]={
BLACK,
VERY_LIGHT_GRAY_BLUE,
WHITE,
LIGHT_GRAY_BLUE,
VERY_LIGHT_GRAY_BLUE,
VERY_LIGHT_GRAY_BLUE,
WHITE,
VERY_LIGHT_GRAY_BLUE,
LIGHT_BLUE,
LIGHT_GRAY_BLUE,
VERY_LIGHT_GRAY_BLUE,
LIGHT_BLUE,
WHITE,
};

#endif